services:
  financer-lite:
    build:
      context: .
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    env_file:
      - stack.env
    pull_policy: build
    networks:
      - financer-services_back-end

networks:
  financer-services_back-end:
    external: true
